// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2C10hIzm7FTDuwLMdXS5JvobyezipiQI',
    appId: '1:926967754503:web:57ab218f7f3b423bd79fa2',
    messagingSenderId: '926967754503',
    projectId: 'notes-286dd',
    authDomain: 'notes-286dd.firebaseapp.com',
    storageBucket: 'notes-286dd.firebasestorage.app',
    measurementId: 'G-QC8NFZVXVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3azZg751FVKI2EiXSd6DED5YAOugADqY',
    appId: '1:926967754503:android:c582a15639b25a2cd79fa2',
    messagingSenderId: '926967754503',
    projectId: 'notes-286dd',
    storageBucket: 'notes-286dd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2C10hIzm7FTDuwLMdXS5JvobyezipiQI',
    appId: '1:926967754503:web:7c5b499b99632eb3d79fa2',
    messagingSenderId: '926967754503',
    projectId: 'notes-286dd',
    authDomain: 'notes-286dd.firebaseapp.com',
    storageBucket: 'notes-286dd.firebasestorage.app',
    measurementId: 'G-RVLEP17F5Q',
  );
}
